version: "3.9"

services:
  app:
    build: ./
    ports:
      - "4040:4040"
    environment:
      - DB_URL=${DB_URL}
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db

volumes:
  dbdata:
