version: "3.9"

services:
  app:
    image: mcr.microsoft.com/devcontainers/javascript-node:18
    ports:
      - "4040:4040"
    environment:
      - URL=${URL}
      - DB_URL=${DB_URL}
    depends_on:
      - db
    command: /bin/sh -c "while sleep 1000; do :; done"
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
  tools:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_MONGODB_PORT=27017
volumes:
  dbdata:
